### ISSUE TITLE
TODO for May 2019

### ISSUE THREAD

**Issue by flurmbo** [greenstreetsinitiative/checkin2015#112]
- [ ]  Make database migrations
- [x] Add debug=true and allowed hosts to config
- [x] Order transportation modes on survey form
- [x] Update leaderboard route redirect to use settings.YEAR
- [ ] Switch order of normal commute and walk-ride day commute on survey

**Comment by flurmbo** [comment]
Database migrations are tricky at the moment. The current hack works for the live site, but Django wants to make another migration on my local build. This might be because a migration was made without being committed at some point.  If I commit the new migration, the live site doesn't like it because it has already made the changes but doesn't recognized the migration's file name.

Right now a hack will work. I made the hack by omitting the migration my local machine wanted, and then rewriting the dependency in the migration from the new changes to depend on the last committed migration.

Someone will need to look at how to open a remote shell on OpenShift, then find out what the name of the migration is in Django's migration table there.
